codecov:
  bot: "codecov-io"
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default: off
      unit:
        target: 90%
        flags: unit
      features:
        target: 50%
        flags: features
    patch:
      default:
        if_no_uploads: error
    changes: true
  ignore:
    - "spec/*"
comment:
  layout: "header, diff, changes, suggestions"
  behavior: default
