# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: postgresql
  database: rails_materialize_development
  min_messages: WARNING
  pool: 5
  username: postgres
  password: password
  host: db

test:
  <<: *default
  database: rails_materialize_test
#
# production:
#   adapter: postgresql
#   url: <%= ENV["POSTGRESQL_URL"] ||  ENV['DATABASE_URL'] || '' %>
#   pool: 15
